### ISSUE TITLE
Replace chat with ytcFilter / Only show ytcFilter

### ISSUE THREAD

**Issue by ErikHumphrey** [RomainLK/ytc-filter#15]
#### Feature request / enhancement

For users that don't care about any of the chat but what matches their filters, it would be nice to have the ability to be able to only see the filtered chat and not the original chat box.

In other words, there could be an option to have ytcFilter take the position/size of the original chat box, and not show the original chat box, visually replacing it.

**Comment by RomainLK** [comment]
For the next version, I have already increased the possible value for the slider. Actually I think I will try to have to limit the max value so that it correspond to the size it needs to completely replace Youtube's chat. Or just a checkbox for "replace", unsure yet.

**Comment by RomainLK** [comment]
Implemented in 1.6.0 with "auto max height" option
