### ISSUE TITLE
Default profile isn't selected by default

### ISSUE THREAD

**Issue by seankao31** [RomainLK/ytc-filter#19]
It seems that after the recent update, default profile isn't automatically selected and applied to the filter.
I have to explicitly
go to Options->Profile->choose default profile->Apply
every time.
After default profile is applied, if I hide the chat room and then show it again, default is no longer applied.

**Comment by RomainLK** [comment]
I forgot to make a migration system from old profile system to new one... :( I will add it. And also a documentation for the new one.

In the mean time, in the new profile menu, there is a new "set as global default" button which you should try. If it doesn't work, create a new profile and use that one. You may delete the old default one.

**Comment by seankao31** [comment]
It seems both aren't working.
Set as global default result in the following error
<img width="521" alt="Screen Shot 2020-09-28 at 4 00 28 PM" src="https://user-images.githubusercontent.com/11817102/94406042-febc9180-01a3-11eb-9c7d-fc76859662e0.png">

And when creating a new profile and trying to save it, the following happens
<img width="523" alt="Screen Shot 2020-09-28 at 3 58 42 PM" src="https://user-images.githubusercontent.com/11817102/94406162-30355d00-01a4-11eb-9517-fcfa74a12f3a.png">

By the way, when applying the default profile, the notification says "undefined" instead of "default".
<img width="263" alt="Screen Shot 2020-09-28 at 4 04 20 PM" src="https://user-images.githubusercontent.com/11817102/94406280-58bd5700-01a4-11eb-940b-28c904aca9df.png">
But when applying a new profile that I created, the name displays correctly. (I can't save that profile tho.)

**Comment by RomainLK** [comment]
The "undefined" is part of the migration problem. There is no name on the profile. The default you see in the dropdown is the technical name. So you can add a name to avoid the "undefined" but well you can't save either.

Concerning your save problem, thanks for your report.  I knew it would happen in one way or another but couldn't really test it. Basically, the extension used all the space it could use within your browser. For now, your fix is either to use the "Clear chat" to make some room. Or you reinstall the extension. You can import your filters before doing so. I will add a few options to manage all of this later, and a quick fix like limiting storage length to 7 days for now.

Now it may help me if you can detail a bit how you use the extension to determine the limit. How long have you been using the extension? Did you use the filter to get lots of messages like lots of messages or just a few? A general idea of how many videos you used it on.

**Comment by seankao31** [comment]
"Clear chat" itself also generate that "Uncaught (in promise)" error with the message "QUOTA_BYTES quota exceeded". I'll try reinstalling the extension then.

I've been using this extension for 1 straight month, about 12~15 hours a day, on 2~4 hololive streams simultaneously. I'm not sure how much message is "a lot" tho. FYI, I use this extension for live translations, and there are quite a lot.

**Comment by seankao31** [comment]
I reinstalled, and it worked like a charm. Thanks.

**Comment by RomainLK** [comment]
Default profile migration is in release 1.6.1. If someone already messed with the profile during version 1.6.0, delete it or give it a name.
