### ISSUE TITLE
View logs

### ISSUE THREAD

**Issue by mjc354** [RomainLK/ytc-filter#30]
Is there a way to view the log of chats that are caught by the filter? The extension seems to save chat when re-opening a YouTube stream that has chat saved, but sometimes streams don't save the chat or their VODs are deleted. Is there anyway to save that log?

(sorry if this isn't the best way to contact you I couldn't find any other method)

**Comment by RomainLK** [comment]
I accept contact in most channels like Github, Discord, or Reddit. Other channels are not really monitored so I only see message late, like in reviews.

There is currently no way to view logs. This would be a feature which I should add when I have an interface to manage memory, reason being that the extension is only allowed a limited size.

**Comment by RomainLK** [comment]
Added in v2 through Archive feature
