### ISSUE TITLE
Filter for verified accounts

### ISSUE THREAD

**Issue by SharkWipf** [RomainLK/ytc-filter#31]
It would be useful to have a filter to verified accounts, similar to the owner/moderator/member filters, since occasionally big-name verified accounts with no direct relation to the channel show up in chat (like i.e. Discord showing up in chat recently).

**Comment by RomainLK** [comment]
I planned to add it with #28 . That other tickets just reflect word for word the request I got on Discord

**Comment by RomainLK** [comment]
Implemented in 1.8.0.
