### ISSUE TITLE
Option to pop out the ytc-filter chat?

### ISSUE THREAD

**Issue by Duskmourne** [RomainLK/ytc-filter#36]
I'm wondering if it's possible to add a feature that allows you to pop out the chat, similar to the YT chat. 

In a lot of cases popping out the YouTube chat suffices, but sadly when watching something archived you lose the option to do so.

**Comment by RomainLK** [comment]
I have some prototyping in the future to do which involves moving everything to another window so this feature may happen as a side effect.

**Comment by RomainLK** [comment]
I have been experimenting for #33  and sadly, I don't think it's possible to make a popout chat for VOD. Youtube disables their livechat after a stream ends, and trying to reuse their popout doesn't work. Using their iframe URL doesn't work either as it needs a domain, which an extension can't have. I'm not even sure if it would work using the iframe URL.

ytcFilter however, will probably manage to popout, if that's what you requested more precisely.

**Comment by RomainLK** [comment]
Done with v2
