### ISSUE TITLE
Question about multiple filters

### ISSUE THREAD

**Issue by raniesantos** [RomainLK/ytc-filter#38]
If I have a regex filter and a moderator filter, will the moderator messages still show up even if their message **doesn't** match the regex???

Are the filters treated with an **AND** logic (fulill all conditions) or an **OR** logic (fulfill at least one condition)??

**Comment by RomainLK** [comment]
For now they are all treated with OR logic. Ticket #14  aims at addressing this problem. I have some thought on how I will be able to include the feature but I have some ground work to do before which leads to version 2.0, mainly #33 #17 #16

**Comment by raniesantos** [comment]
Thanks for the reply. I actually prefer the OR logic.

My regex matches messages that contain at least 2 english letters `A-Za-z` to reduce the visual clutter of Japanese chat messages.

However I'm not able to test easily if I would still be able to see moderator/owner messages even if it is all in Japanese, so I just asked directly here.
