### ISSUE TITLE
Firefox 83 Breaks Usage

### ISSUE THREAD

**Issue by novaex-2b** [RomainLK/ytc-filter#41]
After updating to the most recent firefox (83) ytcFilter no longer shows up on youtube live chat. I tried a downgrade to 75 to check if this was the case and it worked again; it was the only other version I had available in cache to downgrade to.

**Comment by RomainLK** [comment]
Hello. That's strange, I'm using version 83 and it does appear and work on videos. Could you check your extension settings to see if it's still enabled? A change between version may have disabled it if they  changed their security policy for extension. At worst, try reinstalling the extension.

**Comment by novaex-2b** [comment]
I have tried to do a reinstall as well as an enable toggle (classic turn it off and on again). Sometimes it works on a live, sometimes it doesn't. It almost never works on VODs of streams after updating (to firefox 83) though.

**Comment by RomainLK** [comment]
Ok, this won't be easy for me to find out what is happening. I suppose that you meant that not even the blue button in the top right corner appears.

I haven't put a lot of information there but could you check your browser's console? There is two messages being logged when starting ( one is a leftover ):

- Loading ytcFilter
- V 1.8.0 1.8.0

Also a link to the VOD posing issue could be worth a try.

**Comment by novaex-2b** [comment]
Yeah, sorry for not being more specific. The actual element itself, the ytc menu doesn't even load in. I had watched this stream live and ytc worked fine: [Polka Necrobarista](https://www.youtube.com/watch?v=K0xhDJl4Ofo). However now when I try to watch the VOD ytc doesn't appear. After checking the console I found that on lives that it does work it has both outputs you gave appear; Loading ytcFilter and V 1.8.0 both appear. Yet on the VOD that I linked it only shows Loading ytcFilter.

**Comment by RomainLK** [comment]
Ok, thanks for the details. Of course it wouldn't be fun if I could reproduce your issue.

From the look of it, the extension is loaded but the core isn't. I'm not sure how it can happen considering that it should be loaded before the chat to avoid race condition, but, anything is possible. I will address your bug in two ways.

- By default, the extension, will have a "ytcFilter is loading. Please click here if it failed" message, which will allow you to manually bootstrap the core.
- I will add more debug log to better understand what is going on.

**Comment by novaex-2b** [comment]
I tried to do some more delving to try and help out and found out a fix until your bug fixes are released (maybe it will help you identify what's happening as well). I tried using the extension in a private window on a whim and to my surprise it worked. Next I tried sequentially enabling my extensions to see if any of them were causing interference. None of them were the issue, so my next area to look into was cookies (don't know why). I cleared out the browser storage for youtube and bam! Working again. Then I went back to check the console on a page load and noticed there were some warnings about cookies misusing 'SameSite'. I don't know if this helps you, but this is what I was able to discover.

**Comment by RomainLK** [comment]
SameSite doesn't matter since it's a warning of the browser about the website you are currently visiting.

Private window is interesting... Also, emptying the storage. Are you a heavy user of ytcFilter? How many messages do you estimate get captured in a period of 14 days? ytc stores all messages that passed a filter. If there is a lot , it can hit the limit of the browser for extension and I currently have no automatic cleaning except a limit of 14 days.

**Comment by novaex-2b** [comment]
Pretty heavy user. Over 14 days I'd say a conservative estimate would easily hit 8k~ total.

**Comment by BatedUrGonnaDie** [comment]
I'll chime in as well.  Previously working with no issues, then yesterday it stopped showing up in FF completely.  Tried clearing my youtube site data like novaex-2b suggested and then the button popped back up above chat instantly.  I still have my old saved messages, not sure if that is intended.

**Comment by RomainLK** [comment]
I have added some workaround in v2 which may or may not help. This issue will  be closed for now but if there more issue, you can reopen or make a new ticket.
