### ISSUE TITLE
Cannot install add-on because it's missing it's ID

### ISSUE THREAD

**Issue by AutomotiveLily** [RomainLK/ytc-filter#43]
I cannot install the add-on because the manifest.json doesn't have add-on ID.

![Screenshot 2020-12-06 134158](https://user-images.githubusercontent.com/33378913/101279351-673e7500-37ca-11eb-9da0-c1947a3b778d.png)

Browser Console:

> 13:45:28.509 1607255128509	addons.xpi	WARN	Download of https://addons.mozilla.org/firefox/downloads/file/3678556/ytcfilter-1.8.0-fx.xpi failed: Error: Cannot find id for addon C:\Users\[...]\AppData\Local\Temp\tmp-rj7.xpi(resource://gre/modules/addons/XPIInstall.jsm:1539:19) JS Stack trace: loadManifest@XPIInstall.jsm:1539:19
> async*onStopRequest@XPIInstall.jsm:2443:14

More info: https://developer.mozilla.org/fi/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

Windows 10 Education 20H2 19042.630
Firefox 83.0 (64-bit)

**Comment by RomainLK** [comment]
Hello.

Another strange bug... I can't reproduce it at all on my Windows, Linux, or MacOS when trying to install on their Firefox.

From what I have read of the [id documentation](https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/#when-do-you-need-an-add-on-id), this id is optional unless I use some specific feature which I currently don't as far as I know. Some library could but I would expect such an issue to be far more common in that case.

Considering that you have the path to the xpi file being downloaded, could you compute its sha1 ( or another algorithm if you wish) and compare with mine.
Here is the one I got from Mozilla: a94eea601d429391f767b6588088facf22bcede9

Ultimately I may add this id though, I will probably need it in the future as I may need some of these features.

**Comment by AutomotiveLily** [comment]
Couldn't grab the file from the temp folder as it's deleted by Firefox pretty much immediately, but here's what I got from Add-Ons page with "Save link as":
```
//
// File Checksum Integrity Verifier version 2.05.
//
                MD5                             SHA-1
-------------------------------------------------------------------------
7130b97895aeee4e1e05cf49c4616742 a94eea601d429391f767b6588088facf22bcede9 ytcfilter-1.8.0-fx.xpi
```

Also tried dragging the file into Firefox, or "Install add-on from file": both give corrupted add-on error.
And yeah, I can see that others have already installed this add-on without trouble, so at this point it must be something with my installation of Firefox.

**Comment by AutomotiveLily** [comment]
I did some quick testing on an old laptop, and a fresh install of Firefox 83 had no problems installing the add-on. Looks like there's something wrong with my Firefox, so I guess this issue can be closed. Sorry to bother you!

**Comment by RomainLK** [comment]
Thanks for testing on another machine, it will avoid me a wild goose chase. Good luck on fixing your Firefox.
