### ISSUE TITLE
Add-on not loading properly

### ISSUE THREAD

**Issue by TehFreek** [RomainLK/ytc-filter#44]
The Add-on Manager says that the add-on is enabled, the button appears on the toolbar, but clicking the button only results in the text "VChatter will be above the livechat on Youtube ". Have uninstalled and reinstalled the add-on multiple times.

User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0

**Comment by RomainLK** [comment]
For extension, as far as I know, the toolbar button is compulsory, so I had to have it, but it does nothing. ytcFilter instead, add a button directly on Youtube's livechat, just above "Top chat" and their err, burger menu.

Additionally, you may check ticket #41 as some people had issue with Firefox 83 which I have yet to resolve.

**Comment by TehFreek** [comment]
Okay, I removed all my YouTube site data as suggested in the other issue and the ytcFilter button showed up. Sorry about this and thank you.
