### ISSUE TITLE
Exclusion feature

### ISSUE THREAD

**Issue by Per6** [RomainLK/ytc-filter#46]
I would like an option to exclude certain messages since some youtube chats just spam E sometimes

**Comment by RomainLK** [comment]
In the Github wiki, there is a regex cookbook, and there is one for word exclusion:

`/^(?!.*(firstWord|secondWord))/i`

Just replace `firstWord` and `secondWord`by whatever you want, and add a pipe `|` if you need more.

There will also be a huge upgrade to filters with #14 which will make this easier to write, and with better fine tuning.
