### ISSUE TITLE
New permissions in v2.0.0

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [RomainLK/ytc-filter#50]
I'm curious about why the extension needs the new permissions for all tab data access in FF and read browser history in chrome.  Previously it only need it for youtube.com and studio.youtube.com, which makes sense.

**Comment by matthew0x40** [comment]
It seems to have been an accident, if you look at the changelog file (https://github.com/RomainLK/ytc-filter/blob/master/changelog.md) it seems like it'll be rolled back in v2.0.2

**Comment by BatedUrGonnaDie** [comment]
@matthew0x40 Ah, didn't go through the changelog looking for a mention of it.  Thanks for the heads up, I see that 2.0.2 no longer is prompting me for the additional permission in Chrome.
