### ISSUE TITLE
Not working on firefox

### ISSUE THREAD

**Issue by cerovest** [RomainLK/ytc-filter#55]
I used it without any problems until the 2.0.3 update, and now it's just don't appear anymore. (firefox 84.0.1 windows)

**Comment by RomainLK** [comment]
If you feel comfortable, can you access "about:debugging" This Firefox > ytcFilter > Inspect. It will open the debugger for the extension. Check that there is no error message in the console, then you can access the storage tab > Extension storage. There will be an entry @@vwe-persistence ( or a name close to it). A copy of the content of this key could help me debug. Then you can delete it, and restart your browser.

Otherwise, for a simple fix, can you try to remove the extension, close Firefox, then reinstall?

**Comment by cerovest** [comment]
i downgraded it to use it and on reinstallation of the 2.0.3 it worked fine, if it happen again i'll do what you ask.

**Comment by cerovest** [comment]
i still went to the debug and...
![firefox_ZKhebVrBv3](https://user-images.githubusercontent.com/52970171/103419365-0de02080-4b93-11eb-8e84-ba48597f6313.png)

**Comment by Flat** [comment]
Same issue, This is the debug log.

> bootstrap-start 15 background.js:13:30100
> Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 14 background.js:1738
>     send moz-extension://504da544-19a9-47ea-aeaf-afac1389c85c/background.js:1738
> Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 webrequest.js:107
>     onBeforeRequest moz-extension://5f72115d-a064-48cd-97e0-d7d8977f1d92/js/webrequest.js:107
> Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 246 background.js:1738
>     send moz-extension://504da544-19a9-47ea-aeaf-afac1389c85c/background.js:1738

**Comment by RomainLK** [comment]
> i still went to the debug and...
> ![firefox_ZKhebVrBv3](https://user-images.githubusercontent.com/52970171/103419365-0de02080-4b93-11eb-8e84-ba48597f6313.png)
> (but that's not your addon so...)

I'm not sure I understand. Do you still have some problem?

**Comment by cerovest** [comment]
> I'm not sure I understand. Do you still have some problem?
not for now

**Comment by RomainLK** [comment]
Considering that the rush of issues from 2.0.x seems to have ended, I'm closing this ticket.

**Comment by HyphenSam** [comment]
Same issue, I still can't get this add-on working since the 2.0.3 update. I'm on version 2.1.0
The debugger from about:debugging doesn't show anything useful.

![Toolbox_-_Extension__ytcFilter_—_Mozilla_Firefox_2021-01-17_13-11-51](https://user-images.githubusercontent.com/10070018/104827707-aaa9fa00-58c5-11eb-82e5-d8b34b746497.png)

But viewing the web console when loading a livestream displays a TypeError message:

![ytc debug](https://user-images.githubusercontent.com/10070018/104827720-d331f400-58c5-11eb-92e3-e410f991c779.png)


```
[ytcFilter] Loading message insertion loading.js:21:166235
[ytcFilter] Loading message inserted loading.js:21:166587
[ytcFilter] DOM loaded. content.js:21:166735
[ytcFilter] Primary element: true  Message Mount from DOM loaded content.js:21:142557
[ytcFilter] Mounted hook start content.js:21:130149
[ytcFilter] Mounting content.js:21:142690
[ytcFilter] Bootstraping content.js:21:130573
[ytcFilter] Last version detected: 0.0.0 content.js:21:134355
[ytcFilter] Current version: 2.1.0 content.js:21:134455
TypeError: e.global.profiles is undefined
    n moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    c moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    _invoke moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    y moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    Q moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    a moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    tt moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    tt moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    checkUpdate moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    e moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    c moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    _invoke moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    y moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    Q moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    a moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
content.js:7:11714
qt moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    Gt moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    Ht moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    Vt moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    (Async: promise callback)
    Vt moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    tn moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    insert moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    O moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    Bo moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    _update moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    r moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    get moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    hn moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    mount moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    $mount moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    $mount moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:7
    ut moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    t moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    c moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    _invoke moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    y moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/loading.js:15
    o moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    s moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    s moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    e moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    s moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    (Async: EventListener.handleEvent)
    <anonymous> moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:21
    n moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:1
    <anonymous> moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:1
    <anonymous> moz-extension://9529e87a-4fdc-4c5c-a00f-2ce1c95ba533/content.js:1
```

I'm on Firefox 84.0.2 Windows.

**Comment by RomainLK** [comment]
@HyphenSam Have you tried the fixes I put in the second comment of this issue?

**Comment by HyphenSam** [comment]
> @HyphenSam Have you tried the fixes I put in the second comment of this issue?

I actually haven't tried that. Would removing it make me lose the filters I set up?

I'll try doing it once my computer is fixed.

**Comment by RomainLK** [comment]
Considering the error message, it seems you already lost your profiles. On the other hand, if you have a video with your filters still configured, you can export them and reimport later.

**Comment by HyphenSam** [comment]
Okay, that fixed it. Lost my profiles, but the default English preset should suffice.
