### ISSUE TITLE
[request] option to clear archive on end of session

### ISSUE THREAD

**Issue by Newtrin0** [RomainLK/ytc-filter#56]
the archive section fills up over time and starts causing problems when it reaches its max size from what I have seen, it would be nice to be able to have the option to have the archive delete itself when the tab running ytcfilter is closed, my coding knowledge is garbage, only a tiny bit of java and python, so if this is either impossible or would just be a massive pain to implement then feel free to close this without a response.

**Comment by RomainLK** [comment]
It shouldn't be hard to implement, but it depends a bit of what is available to me from the browser. I have planned to have storage warning, and also autocleaning in the future.

**Comment by Newtrin0** [comment]
Good to hear, keep up the good work, this plugin is a real life saver

**Comment by RomainLK** [comment]
As  I feared, browsers don't have any event fired for extension when they are closed

https://bugs.chromium.org/p/chromium/issues/detail?id=30885

At the tab level, I need to check. I hope I won't need the tab permission, or that Google will not mess again with the permission...

**Comment by RomainLK** [comment]
Autocleaning has been added in 2.1.0. It's not exactly at the end of the session, but a number of days after the last time you viewed a video. I hope this will answer your feature request for now.

2.1.0 release will be first on Firefox, and there might be some delay with Google just so I can manage the release, but they can also take their sweet time during review.
