### ISSUE TITLE
ytcfilter no longer shows superchat colors

### ISSUE THREAD

**Issue by dlove67** [RomainLK/ytc-filter#59]
When filtering for superchats in version 2.1.1 in firefox 84.0.2, ytcfilter no longer shows the color of the superchat, though it does capture the amount.

This is helpful with different currencies to see what youtube tags them as.

**Comment by RomainLK** [comment]
Could you link me a stream with a timestamp of when it happens please?

**Comment by RomainLK** [comment]
Nevermind, it's for alll superchat... I will see what I can do to reverse engineer the colors with the new fetch interceptor

**Comment by dlove67** [comment]
And it's working again! Thanks for the quick turnaround!
