### ISSUE TITLE
Livechat "chat disconnected". Incompatibility between extensions

### ISSUE THREAD

**Issue by AraghastThePillager** [RomainLK/ytc-filter#60]
Ytc-Filter Auto Disconnect Chat & Doesn't work on Firefox 84.0.2 (64-bit)
I don't know how to fix this but it work on Chrome Latest Version  - Is there anyway workaround to fix this?

Chat disconnected. Please wait while we try to reconnect you

Disabling the Extension make the SuperChat work - Other Translation tool work but I liked Ytc-Filter best

**Comment by RomainLK** [comment]
Which version of the extension do you have? 2.1.2?

Could you check your console to see if there is any error message please?

**Comment by waycooler** [comment]
I was about to comment before I realized the OP mentioned using other translation tools, and I had both ytcFilter and LiveTL enabled. Disabling LiveTL got rid of the browser console errors, and I can see chat again normally after refreshing the page. I don't mind disabling it, though; I wasn't using it anyway. Leaving what I wrote before; I hope it's helpful at least in figuring out what's conflicting:

> I'm having the same issue, since 2.1.0, I think. It's happening in 2.1.2 either way. Firefox is v84.0.2, 64-bit, on Manjaro Linux. Every stream or vod I open on Youtube can't successfully connect to the chat.
> 
> It manifests on the stream/vod page in the chat as just these two lines:
> 
>   Chat disconnected. Please wait while we try to reconnect you.
>   Unable to connect to chat. Please try again later. 
> 
> And the following looks to be spamming the Browser Console:
>   
>   Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 80 background.js:46
>       <anonymous> moz-extension://d5b0cf48-4504-40cc-9237-3fe4c4bf67c0/js/background.js:46
>     
> There are also errors in the Web Console, but I'm not sure those are related. They still pop up with ytcFilter disabled.

**Comment by AraghastThePillager** [comment]
https://i.imgur.com/UEmI13b.png Yes 2.1.2 that how look the console to me.  it seem to me though the error only started to happen since 2.1.1 / 2.1.2 update - i had 2.0 before and it was fine.  with multiple stream open at same time even

**Comment by AraghastThePillager** [comment]
> 
> 
> I was about to comment before I realized the OP mentioned using other translation tools, and I had both ytcFilter and LiveTL enabled. Disabling LiveTL got rid of the browser console errors, and I can see chat again normally after refreshing the page. I don't mind disabling it, though; I wasn't using it anyway. Leaving what I wrote before; I hope it's helpful at least in figuring out what's conflicting:

hey that fixed it - i had both i guess it conflict now? but not in chrome thank for the information.

**Comment by RomainLK** [comment]
I see. I will test both extension together later and see, but it's highly possible there is conflict for the simple reason that since we both have extension which had performance issues, we may have optimizations which are not compatible together.

**Comment by RomainLK** [comment]
Fixed in 2.1.3
