### ISSUE TITLE
High CPU and Memory usage after update(?)

### ISSUE THREAD

**Issue by Lucky2307** [RomainLK/ytc-filter#61]
![Untitled-1](https://user-images.githubusercontent.com/11814787/105175737-ead3db80-5b56-11eb-8f08-bf6b1e5f0803.jpg)

As you can see from the screenshot above, CPU maxed out and Memory kept climbing indefinitely. Started happening a few hours ago which I suspect when the latest update rolled out.
Stopped happening after I disabled the extension.

Windows 10 Version 2004 Build 19041.746
Microsoft Edge Version 87.0.664.75 (Official build) (64-bit)
ytcFilter Version 2.1.2

**Comment by RomainLK** [comment]
Hm I haven't tested with Edge. For now, how often do you use ytcFilter? Ideally I would need you to access the popout to see the size of your archive.

When did the CPU usage peak? Right when starting a video after the update or later?

In any case, I suggest if possible, to Popout > Help > Full Reset. Otherwise, uninstall, close your browser then reinstall.

**Comment by Lucky2307** [comment]
Seems like doing the full reset fixed it.

To answer your questions:
- I've been using ytcFilter for quiet a while now. Can't remember when exactly I installed but iirc it has been atleast a month.
- The CPU peaked right after I clicked on the live. I use GPU for video decoding so I know it's not the problem. A few hours before I opened the issue, it was working fine. I started having this issue about half an hour before I posted the issue. I assume ms Edge updated it automatically while I was still using it. 
- When I was having the issue I only had one live opened.

**Comment by RomainLK** [comment]
Ok, you have one of this very rare case that I can't easily identify. Chance are you had huge archive which needed to migrate. Though I already tried with an archive of 130 videos in Firefox, and it tooks a few seconds and 450mb of RAM to migrate, then have it go down to 76mb when it's done. Still nothing like you described.

I will keep the issue open for now in case someone else encounter the issue during the update. As for a fix, just in case but I will overhaul the migration system in 3.0.0 to bypass a number of things which may increase CPU/RAM usage.

**Comment by DDDespair** [comment]
Having the same issue. Huge CPU/RAM spikes in Chromium the moment I click on a livestream. The Popout/Settings button wouldn't work at all, so I'll try a reinstall.

**Comment by RomainLK** [comment]
I have a fix for migration in 2.1.3, not sure if it will be useful considering migration for everyone should be done by now.

@DDDespair If you open the console of the popout, do you have any error message before or after pressing the "Show settings" button?

**Comment by DDDespair** [comment]
No. On pressing "Popout/Settings" I get a full size window https://i.imgur.com/SjXbq9G.jpg When I hit "Show Settings" it resizes to https://i.imgur.com/Iw7gNh1.jpg but displays nothing else. The chat messages do show up on the popout window, it just has my global default of staff/mod messages applied. I'm just not sure why the initial had the settings button work but it doesn't now.

**Comment by RomainLK** [comment]
By console, I meant opening the debugger with F12 when the focus is inside the popout, then accessing the console tab of the debugger. Error message would appear there. 
Last time I had such issue, it's again the storage being corrupted, so for end user, aside of reinstalling, after closing the browser there is not much you can do without dwelving deeper.

If you can, it would help me debug if you can extract the content of your storage. In order to do so, in the console of the popout, you paste the following code at the bottom of the console.
`chrome.storage.local.get(s => console.log(JSON.stringify(s)))`

**Comment by DDDespair** [comment]
Ah, I see. Console shows this

```
 popout-main.js:7 TypeError: Cannot read property 'default' of undefined
     at channelArchive (popout-main.js:21)
     at r.forEachGetter.t._wrappedGetters.(chrome-extension://mnldnbhgfocmkehnlkeanlhfmopepnko/anonymous function) (chrome-extension://mnldnbhgfocmkehnlkeanlhfmopepnko/popout-main.js:15:111736)
     at Pn.<anonymous> (popout-main.js:15)
     at hn.get (popout-main.js:7)
     at hn.evaluate (popout-main.js:7)
     at Pn.channelArchive (popout-main.js:7)
     at Object.get [as channelArchive] (popout-main.js:15)
     at a.<anonymous> (popout-main.js:38)
     at a.t._render (popout-main.js:7)
     at a.r (popout-main.js:7)
```
Here's a link to what the debug command spit out https://litter.catbox.moe/5xpvjh.txt

**Comment by RomainLK** [comment]
Thanks for your help. I now have an hint of what the issue could be. It needs further investigation for now but I should have some fix for next release. I have opened ticket #69 for your problem and will close this one as it's not linked.

As a workaround, I'm sorry to say this but you will have to retry uninstalling, closing your browser, then reinstalling. So far it seems like you found a very rare bug, and most people have been successful doing so. I hope it won't happen again, or you can post in the other ticket if it does.
