### ISSUE TITLE
"Extension Storage" Percentage is Backwards

### ISSUE THREAD

**Issue by Yay295** [RomainLK/ytc-filter#62]
For me it currently shows `Extension storage (not real time): 1709/5242880 (100%)`, but 1709/5242880 is 0.03%.

**Comment by RomainLK** [comment]
Ah lol... I copy pasted the formula for the remaining space which I used for the warning... I will update it with another release.

**Comment by RomainLK** [comment]
Fix is with the 2.1.4 beta. I will close ticket after official release

**Comment by RomainLK** [comment]
2.1.4 released for Firefox. Chrome will be slightly later, after some testing has been done with Firefox and when Google finishes reviewing it.

**Comment by RomainLK** [comment]
Reopening... guess there is change of branch which didn't go properly orz

**Comment by RomainLK** [comment]
Re fixed in 2.1.6 x.x
