### ISSUE TITLE
Chat disconnected after certain amount of time

### ISSUE THREAD

**Issue by qadzifi** [RomainLK/ytc-filter#63]
I have ytcfilter installed.

When I open youtube livestream my youtube live chat is disconnected after a certain amount of time. I disable the extension and reload youtube livestream page and my chat never disconnected again, because of that I assume this is the issue related with this extension.

I'm using opera gx
![image](https://user-images.githubusercontent.com/20248047/105488603-76c73e00-5ce4-11eb-97a0-c887a0c07276.png)

**Comment by RomainLK** [comment]
Are you using another extension like LiveTL? If so there is a conflict between the 2 which is fixed in ytcFilter 2.1.3. The new version is already available on Firefox, but Google is slow. If so, you can install straight from the release package from Github.

**Comment by qadzifi** [comment]
Looks like it, I have 2.1.3 for now. So far not disconnected with LiveTL enabled

**Comment by kana-mycin** [comment]
I had the same issue on 2.1.2 and 2.1.3 seems to have fixed it.

**Comment by RomainLK** [comment]
Review finally ended for Chrome so 2.1.3 is officially released for those browsers
