### ISSUE TITLE
"Filter type: Author is moderator" does not work

### ISSUE THREAD

**Issue by lttjohn** [RomainLK/ytc-filter#68]
As title, I tested other filters like superchat and user name and all of them works fine.

**Comment by RomainLK** [comment]
What is your Youtube's language? In 2.1.2, the roles filter worked only in English. 2.1.3 fixes this, but Google is super slow with review. Firefox already has the update.

**Comment by lttjohn** [comment]
Yes, you are right. I am using ver 2.1.2 in Chrome and Youtube is not in English.
I will using firefox instead until Chrome store update to the new version.
Thank you.
