### ISSUE TITLE
RegEx Matching Always Case-Sensitive

### ISSUE THREAD

**Issue by Yay295** [RomainLK/ytc-filter#7]
RegEx matching seems to always be case sensitive, even when the "case sensitive" box isn't checked.

**Comment by RomainLK** [comment]
This is by design. You may have noticed that the case sensitive box is disabled. That's because for regular expression, you should use the "i" flag for case insensitivity. Example: `/[a-z]/i`

**Comment by Yay295** [comment]
I didn't notice the box was disabled. It looks like you have the wrong ID specified.

```html
<div class="vc-options-item flex-align-center">
  <label for="filter">Case sensitive:</label>
  <input id="case-sensitive" type="checkbox">
  <button type="submit">Add</button>
</div>
```
