### ISSUE TITLE
Some filter does not work when YouTube isn't in English

### ISSUE THREAD

**Issue by oOBoomberOo** [RomainLK/ytc-filter#70]
Affected filters:
- Author is member
- Author is moderator
- Author is owner
- Author is verified

These filters didn't catch chat messages that should be included when you switch your YouTube language to anything other than English.

Tested languages (but all non-English language should be affected):
- Japanese
- Thai
- German
- Spanish

**Comment by RomainLK** [comment]
It's fixed in 2.1.3 which was released 3 days ago. Now, the problem is, Google is taking their sweet time to review... If you are in hurry, you can take the package release on Github.

**Comment by oOBoomberOo** [comment]
Ah, alright I will use that for now then.
