### ISSUE TITLE
ytcFilter loading ( Youtube update )

### ISSUE THREAD

**Issue by blaxter75** [RomainLK/ytc-filter#71]
Downloaded 2.1.3 off Github just to see if it would fix my random loading issues (ytc was working but it started acted up requiring me to click the "if there's a problem loading" to load it every time)

Installing it gave an error box in the Extensions window stating:

Unrecognized manifest key 'browser_specific_settings' with the following code block highlighted (ln 55-60):

  "browser_specific_settings": {
    "gecko": {
      "id": "{20f2dcdf-6f8d-4aeb-862b-b13174475d9c}",
      "strict_min_version": "48.0"
    }
  }

**Comment by RomainLK** [comment]
For the "if there's a problem loading": is your browser rather slow? ytcFilter expect the chat to have started loading, but if not, it will fail. Restarting your browser or checking if there is anything slowing it down could help. I will try to have something in the next release to take into account slow browsers.

As for the error message, it's not a problem. That's a configuration specific to Firefox which Chrome doesn't recognize and ignore.

**Comment by blaxter75** [comment]
I have no idea what the measure for slow is now. I use a cheap laptop to stream while I am working so maybe? It's an Intel i3 with 8GB of RAM that eventually starts to cry if I leave the streams open too long without restarting them because Chrome is terrible with memory management.

To test, there's currently Choco's stream going on so I reloaded it and it took about 2 seconds for the chat window to come up. It takes a little longer if it's a stream that has been running for a while like Botan's was an hour in and that took about 3-4 seconds to load the chat frame.

**Comment by RomainLK** [comment]
Hm, yeah that kind of config may struggle at some point. Actually, the problem is visible in the console with  a log which says
` [ytcFilter] Primary element: false` when it should be true.

The "click here if it fails" was a feature which I added as a blind workaround for a bug which I couldn't reproduce. But now I'm starting to get confirmation that it's due to slow browser.

**Comment by blaxter75** [comment]
I'll post an update somehow if I can catch it if it'll help verify. The click here message hasn't shown up as of my last post

**Comment by RomainLK** [comment]
I have released a beta version of 2.1.4 here on Github. There is a change which aims at being more forgiving with slow browsers. Basically it tries several time to load ytcFilter for 10s after the chat start loading.  If you can try it and tell me if it improves your situation, it would greatly help me validate the beta :)

**Comment by blaxter75** [comment]
Haven't downloaded it yet since I just got home to see this. I'll test it out shortly but I did want to make note that it doesn't appear to be limited to slow browsers. I started seeing the message show up on a system running an i7-9750 with 16GB RAM + RTX 2070.

**Comment by RomainLK** [comment]
Ok great! I will release 2.1.4 sometime this week. There is a bit more polish to do.

**Comment by blaxter75** [comment]
Since I have this ticket open I thought it best to append any 2.1.4 issues to it.

I started up a livestream and it spawned a new error that I haven't yet seen. I am not sure what the error causes but it is happening repeatedly (not a one off error) as it appears once a minute in the devconsole.

It is too long to paste so I am attaching it as a text file.
[errorlog.txt](https://github.com/RomainLK/ytc-filter/files/5886201/errorlog.txt)

**Comment by RomainLK** [comment]
Was this with 2.1.4 beta?

There should actually be a second error message just below that one which gives more details.   If I had to guess, it's due to that one message without an author name. I have a fix for it in 2.1.4, but the problem is it's VERY random issue from Youtube so I can't test it... Actually I will run some offline test to confirm this.

**Comment by RomainLK** [comment]
2.1.4 released for Firefox. Chrome will be slightly later, after some testing has been done with Firefox and when Google finishes reviewing it.

I'm keeping this issue open until it's released for Chrome too as the issue seems to get more and more common.

**Comment by blaxter75** [comment]
Confirming that I am getting the loading button every time no matter how fast the Youtube chat loads. Looks like you might be right with it being a Youtube side change.

Also confirming that my attached error was on 2.1.4 beta. Still running that version. I've not yet run into the long error again so I can't see if there is another error message following it. The randomness of these probably makes this that much harder!

**Comment by RomainLK** [comment]
for that long error message, i have found the issue. I had made a typo in the fix. i added some unit test on my end using your long error message so that i don't have to rely on youtube's random behaviour to test.

if you want, the release package for 2.1.4 stable is on github.

**Comment by blaxter75** [comment]
Downloaded and installed the 2.1.4 stable from Github.

Initial testing on a livestream appeared to go smoothly.

Second run testing on attempting to replay an archived stream results in catching TypeError as follows, no secondary error following:

content.js:46722 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at applyFilter (content.js:46722)
    at _callee3$ (content.js:47353)
    at tryCatch (content.js:30995)
    at Generator.invoke [as _invoke] (content.js:31225)
    at Generator.next (content.js:31050)
    at ytc_filtervue_type_script_lang_js_asyncGeneratorStep (content.js:46799)
    at _next (content.js:46801)
    at content.js:46801
    at new Promise (<anonymous>)
    at content.js:46801

I can't identify exactly what this error does since to me, the filters look to be functioning as translated messages are filtered properly and everything looks to function.

**Comment by RomainLK** [comment]
That error is probably due to an empty message in the chat, or empty author. It shouldn't affect much the working of the extension; these kind of message, especially without author, are a problem from Youtube.

Still I have fixed this in 2.1.5 which is coming soon.

**Comment by blaxter75** [comment]
Don't have an error to correspond to this issue that I discovered testing features. Running the stable 2.1.4 release.

While watching a livestream with YTC active, if I popout the settings window and decide to clear the YTC archives, it appears to break things. When I clear the archive, it clears properly but once that happens and I close the popout window, YTC appears to no longer properly filter messages though it will up the chat counter. It will also not be able to open the popout settings window until I refresh the video page to reload the extension.

**Comment by RomainLK** [comment]
2.1.6 is pushed to review on Chrome. Google can be slow to review unlike Mozilla, so it can take days before the update is available. I will close the ticket once it's published.

**Comment by RomainLK** [comment]
2.1.6 was released after 5 days in Google review hell!
